
Imports System.Data
Imports System.Data.SqlClient
Imports [class].clsWebGeneral
Imports [class].clsGeneralDB
Imports [class].clsGeneral
Imports [class].clsGeneralSetting
Imports [class].clsContentDB
Imports System.Runtime.InteropServices
Imports System.Runtime.Remoting.Activation

Partial Class wc_parentHeader
    Inherits System.Web.UI.UserControl

    Protected rootPath As String = _rootPath

    Protected txtYourNameReqCall As String = ""
    Protected txtNoHpReqCall As String = ""
    Protected txtContactTimesRequestCall As String = ""
    Protected txtChooseProperti As String = ""
    Protected txtContactMessageReqCall As String = ""

    Protected note As String = ""
    Protected noteType As String = ""

    Private Sub bindMenu()

        Dim result As New StringBuilder

        result.Append("    <div class=""navbar-area"">")
        result.Append("        <div class=""mobile-nav"">")
        result.Append("            <a href="+_rootpath+""" class=""logo"">")
        result.Append("                <img  class=""mobile-logo"" align-items-center  width=""200"" src="""+_rootPath +"/Support/img/logoPremier3.png"" class=""logo-one"" alt=""Logo"">")
        'result.Append("               <img width=""100"" height=""100"" src="""+_rootPath +"/Support/img/logoPremier3.png"" class=""logo-one"" alt=""Logo"">")
        result.Append("            </a>")
        result.Append("        </div>")
        result.Append("    </div>")
        result.Append("    <div class=""main-nav"">")
        result.Append("        <div class=""container"">")
        result.Append("            <nav class=""container-max navbar navbar-expand-md navbar-light "">")
        result.Append("                <a class=""navbar-brand"" href="+_rootpath+""">")
        result.Append("                    <img align-items-center width=""150"" height="""" src="""+_rootPath +"/Support/img/logoPremier3.png"" class=""logo-one"" alt=""Logo"">")
        'result.Append("                    <img width=""100"" height=""100"" src="""+_rootPath +"/Support/img/logoPremier3.png"" class=""logo-two"" alt=""Logo"">")
        result.Append("                </a>")
        result.Append("                <div class=""collapse navbar-collapse mean-menu"" id=""navbarSupportedContent"">")
        result.Append("                    <ul class=""navbar-nav m-auto"">")
        result.Append("                        <li class=""nav-item"">")
        result.Append("                            <a href=""#"" class=""nav-link active"">")
        result.Append("                                Home")
        result.Append("                                <i class=""bx bx-chevron-down""></i>")
        result.Append("                            </a>")
        result.Append("                            <ul class=""dropdown-menu"">")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""index.html"" class=""nav-link active"">")
        'result.Append("                                        Home One")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""index-2.html"" class=""nav-link"">")
        'result.Append("                                        Home Two")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""index-3.html"" class=""nav-link"">")
        'result.Append("                                        Home Three")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        result.Append("                            </ul>")
        result.Append("                        </li>")
        result.Append("                        <li class=""nav-item"">")
        result.Append("                            <a href=""#"" class=""nav-link"">")
        result.Append("                                About")
        result.Append("                            </a>")
        result.Append("                        </li>")
        result.Append("                        <li class=""nav-item"">")
        result.Append("                            <a href=""#"" class=""nav-link"">")
        result.Append("                                Pages")
        result.Append("                                <i class=""bx bx-chevron-down""></i>")
        result.Append("                            </a>")
        result.Append("                            <ul class=""dropdown-menu"">")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""gallery.html"" class=""nav-link"">")
        'result.Append("                                        Gallery")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""#"" class=""nav-link"">")
        'result.Append("                                Projects")
        'result.Append("                                <i class=""bx bx-chevron-down""></i>")
        'result.Append("                            </a>")
        'result.Append("                            <ul class=""dropdown-menu"">")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""projects.html"" class=""nav-link"">")
        'result.Append("                                        Projects")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""project-details.html"" class=""nav-link"">")
        'result.Append("                                        Projects details")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                            </ul>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""team.html"" class=""nav-link"">")
        'result.Append("                                Team")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""#"" class=""nav-link"">")
        'result.Append("                                Shop")
        'result.Append("                                <i class=""bx bx-chevron-down""></i>")
        'result.Append("                            </a>")
        'result.Append("                            <ul class=""dropdown-menu"">")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""shop.html"" class=""nav-link"">")
        'result.Append("                                        Shop")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""cart.html"" class=""nav-link"">")
        'result.Append("                                        Cart")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""checkout.html"" class=""nav-link"">")
        'result.Append("                                        Checkout")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""shop-details.html"" class=""nav-link"">")
        'result.Append("                                        Shop Details")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                            </ul>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""faq.html"" class=""nav-link"">")
        'result.Append("                                FAQ")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""book-appointment.html"" class=""nav-link"">")
        'result.Append("                                Book An Appointment")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""testimonials.html"" class=""nav-link"">")
        'result.Append("                                Testimonials")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""#"" class=""nav-link"">")
        'result.Append("                                Property")
        'result.Append("                                <i class=""bx bx-chevron-down""></i>")
        'result.Append("                            </a>")
        'result.Append("                            <ul class=""dropdown-menu"">")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""property.html"" class=""nav-link"">")
        'result.Append("                                        Property")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""property-details.html"" class=""nav-link"">")
        'result.Append("                                        Property details")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                            </ul>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""404.html"" class=""nav-link"">")
        'result.Append("                                404 page")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""#"" class=""nav-link"">")
        'result.Append("                                User")
        'result.Append("                                <i class=""bx bx-chevron-down""></i>")
        'result.Append("                            </a>")
        'result.Append("                            <ul class=""dropdown-menu"">")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""sign-in.html"" class=""nav-link"">")
        'result.Append("                                        Sign In")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""sign-up.html"" class=""nav-link"">")
        'result.Append("                                        Sign Up")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                                <li class=""nav-item"">")
        'result.Append("                                    <a href=""recover-password.html"" class=""nav-link"">")
        'result.Append("                                        Recover Password")
        'result.Append("                                    </a>")
        'result.Append("                                </li>")
        'result.Append("                            </ul>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""terms-condition.html"" class=""nav-link"">")
        'result.Append("                                Terms & Conditions")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""privacy-policy.html"" class=""nav-link"">")
        'result.Append("                                Privacy Policy")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""coming-soon.html"" class=""nav-link"">")
        'result.Append("                                Coming Soon")
        'result.Append("                            </a>")
        result.Append("                        </li>")
        result.Append("                    </ul>")
        result.Append("                </li>")
        result.Append("                <li class=""nav-item"">")
        result.Append("                    <a href=""#"" class=""nav-link"">")
        result.Append("                        Services")
        result.Append("                        <i class=""bx bx-chevron-down""></i>")
        result.Append("                    </a>")
        result.Append("                    <ul class=""dropdown-menu"">")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""services.html"" class=""nav-link"">")
        'result.Append("                                Services")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""service-details.html"" class=""nav-link"">")
        'result.Append("                                Service Details")
        'result.Append("                            </a>")
        result.Append("                        </li>")
        result.Append("                    </ul>")
        result.Append("                </li>")
        result.Append("                <li class=""nav-item"">")
        result.Append("                    <a href=""#"" class=""nav-link"">")
        result.Append("                        Blog")
        result.Append("                        <i class=""bx bx-chevron-down""></i>")
        result.Append("                    </a>")
        result.Append("                    <ul class=""dropdown-menu"">")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""blog.html"" class=""nav-link"">")
        'result.Append("                                Blog")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        'result.Append("                        <li class=""nav-item"">")
        'result.Append("                            <a href=""blog-details.html"" class=""nav-link"">")
        'result.Append("                                Blog Details")
        'result.Append("                            </a>")
        'result.Append("                        </li>")
        result.Append("                    </ul>")
        result.Append("                </li>")
        result.Append("                <li class=""nav-item"">")
        result.Append("                    <a href=""#"" class=""nav-link"">")
        result.Append("                        Contact")
        result.Append("                    </a>")
        result.Append("                </li>")
        result.Append("            </ul>")
        result.Append("            <div class=""side-btn-area"">")
        result.Append("                <a href=""tel:+622122816000"" class=""call-btn"">")
        result.Append("                    <i class=""bx bx-phone""></i>")
        result.Append("                   Hubungi Kami")
        result.Append("                </a>")
        result.Append("            </div>")
        result.Append("            <div class=""appointment-btn"">")
        result.Append("                <a href=""#"" class=""default-btn default-bg-buttercup"">")
        result.Append("                    Contact Us")
        result.Append("                    <i class=""bx bx-right-arrow-alt""></i>")
        result.Append("                </a>")
        result.Append("            </div>")
        result.Append("        </div>")
        result.Append("    </nav>")
        result.Append("</div>")
        result.Append("</div>")
        result.Append("</div>")

        'result.Append("    <div class=""navbar-area"">")
        'result.Append("      <div class=""main-nav"">")
        'result.Append("      <div class=""container-fluid"">")
        'result.Append("         <nav class=""container-max navbar navbar-expand-md navbar-light"">")
        'result.Append("             <a class=""navbar-brand"" href=""index.html"">")
        'result.Append("                 img src="""+_rootPath +"/Support/img/logoPremier3.png"" class=""logo"" alt=""Logo""></a>")
        'result.Append("      <div class=""collapse navbar-collapse mean-menu"" id=""navbarSupportedContent"">")
        'result.Append("         <ul class=""navbar-nav m-auto"">")
        'result.Append("             <li class=""nav-item"">")
        'result.Append("                 <a href=""#"" class=""nav-link active"">Home")
        'result.Append("                    <i class=""bx bx-chevron-down""></i></a>")
        'result.Append("                         <ul class=""dropdown-menu"">")
        'result.Append("                             <li class=""nav-item"">")
        'result.Append("                                 <a href=""index.html"" class=""nav-link active"">Home One</a>")
        'result.Append("                             </li>")
        'result.Append("                         </ul>")
        'result.Append("             </li>")
        'result.Append("             <li class=""nav-item"">")
        'result.Append("                 <a href=""about.html"" class=""nav-link"">About</a>")
        'result.Append("             </li>")
        'result.Append("             <li class=""nav-item"">")
        'result.Append("                 <a href=""#"" class=""nav-link"">Pages")
        'result.Append("                     <i class=""bx bx-chevron-down""></i>")
        'result.Append("                 </a>")
        'result.Append("                         <ul class=""dropdown-menu"">")
        'result.Append("                              <li class=""nav-item"">")
        'result.Append("                                 <a href=""gallery.html"" class=""nav-link"">Gallery</a>")
        'result.Append("                              </li>")
        'result.Append("                         <li class=""nav-item"">")
        'result.Append("                             <a href=""#"" class=""nav-link"">Projects")
        'result.Append("                                 <i class=""bx bx-chevron-down""></i>")
        'result.Append("                             </a>")
        'result.Append("                                     <ul class=""dropdown-menu"">")
        'result.Append("                                         <li class=""nav-item"">")
        'result.Append("                                             <a href=""project.html"" class=""nav-link"">Projects</a>")
        'result.Append("                                         </li>")
        'result.Append("                                         <li class=""nav-item"">")
        'result.Append("                                             <a href=""project-detail.html"" class=""nav-link"">Projects Detail</a>")
        'result.Append("                                         </li>")
        'result.Append("                                     </ul>")
        'result.Append("                         </li>")
        'result.Append("                         <li class=""nav-item"">")
        'result.Append("                             <a href=""team.html"" class=""nav-link"">Team</a>")
        'result.Append("                         </li>")
        'result.Append("                         </ul>")
        'result.Append("             </li>")
        'result.Append("             <li class=""nav-item"">")
        'result.Append("                 <a href=""#"" class=""nav-link"">Services")
        'result.Append("                    i class=""bx bx-chevron-down""></i>")
        'result.Append("                         <ul class=""dropdown-menu"">")
        'result.Append("                             <li class=""nav-item"">")
        'result.Append("                                 <a href=""services.html"" class=""nav-link"">Services</a>")
        'result.Append("                             </li>")
        ' result.Append("                             <li class=""nav-item"">")
        'result.Append("                                 <a href=""services-detail.html"" class=""nav-link"">Services Detail</a>")
        'result.Append("                             </li>")
        'result.Append("                         </ul>")
        'result.Append("             </li>")
        'result.Append("             <li class=""nav-item"">")
        'result.Append("                 <a href=""#"" class=""nav-link"">Blog")
        'result.Append("                     <i class=""bx bx-chevron-down""></i>")
        'result.Append("                 </a>")
        'result.Append("                         <ul class=""dropdown-menu"">")
        'result.Append("                             <li class=""nav-item"">")
        'result.Append("                                 <a href=""blog.html"" class=""nav-link"">Blog</a>")
        'result.Append("                             </li>")
        ' result.Append("                             <li class=""nav-item"">")
        'result.Append("                                 <a href=""blog-detail.html"" class=""nav-link"">Blog Detail</a>")
        'result.Append("                             </li>")
        'result.Append("                         </ul>")
        'result.Append("              </li>")
        'result.Append("             <li class=""nav-item"">")
        'result.Append("                 <a href=""contact.html"" class=""nav-link"">Contact</a>")
        'result.Append("             </li>")
        'result.Append("         </ul>")
        'result.Append("         <div class=""side-btn-area"">")
        'result.Append("             <a href=""tel:+622122816000"" class=""call-btn"">")
        'result.Append("                 <i class=""bx bx-phone""></i>")
        'result.Append("                     +62 2122816000")
        'result.Append("             </a>")
        'result.Append("         </div>")
        'result.Append("         <div class=""appointment-btn"">")
        'result.Append("            <a href=""#"" class=""default-btn default-bg-buttercup"">")
        'result.Append("              Schedule appointment")
        'result.Append("                 <i class=""bx bx-right-arrow-alt""></i>")
        'result.Append("             </a>")
        'result.Append("         </div>")
        'result.Append("        </div>")
        'result.Append("       </nav>")
        'result.Append("      </div>")
        'result.Append("     </div>")
        'result.Append("   </div>")

         ltrMenu.Text = result.ToString()

    End Sub

    Public Shared Function bindPopupRequestCall2() As String
        Dim result As New StringBuilder

        Try
            Dim context As HttpContext = HttpContext.Current
            Dim mobile As HttpBrowserCapabilities = context.Request.Browser
            If mobile.IsMobileDevice Then
                result.Append("<div class=""modal fade"" id=""myModalRequestCall2"" role=""dialog"" style=""background-color: unset;z-index: 1040;"">")
                result.Append("    <div class=""modal-dialog"" style=""margin: -5px auto;"">")
                result.Append("        <div class=""modal-content"">")
                result.Append("            <div class=""modal-header"" style=""text-align:center;"">")
                result.Append("              <button type=""button"" class=""close"" data-dismiss=""modal"" name=""btn-6"">&times;</button>")
                result.Append("              <h4 class=""modal-title"">Hubungi Kami</h4>")
                result.Append("            </div><br>")

                'result.Append("	<div id=""previewMain"">")
                'result.Append("		<div class=""innerMain"">")
                'result.Append("			<div class=""contentMain"">")

                result.Append("                <section class=""section-wrap login-register pt-0 pb-10"">")
                result.Append("                    <div class=""container"" style=""width:100%;"">")
                result.Append("                      <div id=""wrapperformregist"" style=""width:auto;"">")

                result.Append("                       <div class=""row"" style=""margin-bottom: 15px;"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom: 0px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"" >")
                result.Append("                                        Nama Anda")
                result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                    <input type=""text"" id=""txtYourNameReqCall"" name=""txtYourNameReqCall"" class=""input-text"" placeholder=""Masukan nama.."" style=""margin-top:5px;padding: 10px 5px 10px 10px; height: 20px;"" value="""" />")
                result.Append("                                    <label id=""iYourNameReqCall"" class=""invalid-tooltip"" style=""color: #b53838;margin-top: 25px; font-weight: bold; font-size: 10px;    letter-spacing: unset;"">Nama harus diisi</label>")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                        <div class=""row"" style=""margin-bottom: 0px;"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-top: -45px;"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom: 0px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"">")
                result.Append("                                        Nomor Telepon")
                result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                    <input type=""text"" id=""txtNoHpReqCall"" name=""txtNoHpReqCall"" class=""input-text"" placeholder=""Masukan nomor Telepon aktif.."" style=""margin-top:5px;padding: 10px 5px 10px 10px; height: 20px;"" value="""" onkeyup=""javascript:toNumeric(this);"" />")
                result.Append("                                    <label id=""iHPReqCall"" class=""invalid-tooltip"" style=""color: #b53838;margin-top: 25px; font-weight: bold; font-size: 10px; letter-spacing: unset;"">Nomor Telepon harus diisi</label>")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                       <div class=""row"" style=""margin-bottom: 10px;margin-top: -30px;"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom: 15px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"" >")
                result.Append("                                        Email")
                'result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                    <input type=""text"" id=""txtYourEmailReqCall"" name=""txtYourEmailReqCall"" class=""input-text""placeholder=""Masukan Email.."" style=""margin-top:5px;padding: 10px 5px 10px 10px; height: 20px;"" value="""" />")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                        <div class=""row"" style=""margin-bottom: 15px;margin-right: 22px;display:none"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-bottom:0px;margin-top: -60px;"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom:unset;margin-bottom:5px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"">")
                result.Append("                                        Waktu Terbaik untuk menghubungi Anda")
                'result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                </p>")
                result.Append("                                <div class=""form-group"">")
                result.Append("                                    <div style=""width: 101%;padding-left: 5px;"" class=""input-group date form_datetime2 col-md-5"" data-date=""2019-07-16T05:25:00Z"" data-date-format=""dd MM yyyy HH:ii"" data-link-field=""dtp_input1"">")
                result.Append("                                        <input style=""width: 90%;margin-top: 0px;height: 25px;"" class=""form-control"" size=""16"" type=""text"" value=""" + Format(Now, "dd MMMM yyyy HH:mm") + """ readonly id=""txtContactTimesRequestCall"" name=""txtContactTimesRequestCall"" />")
                'result.Append("                                        <span class=""input-group-addon""><span class=""glyphicon glyphicon-remove""></span></span>")
                result.Append("					                    <span class=""input-group-addon""><span class=""glyphicon glyphicon-th""></span></span>")
                result.Append("                                    </div>")
                'result.Append("				                    <input class=""form-control"" id=""txtContactTimeReqCall"" value=""<%=txtContactTimeReqCall %>"" name=""txtContactTimeReqCall"" type=""hidden"" autocomplete=""off"" id=""dtp_input1""  /><br/>")
                result.Append("                                </div>")
                result.Append("                                <div id=""iContactTimeReqCall"" style=""margin-top: -19px;display:;"" >")
                result.Append("                                </div>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                        <div class=""row"" style=""margin-bottom: 33px;display:none"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-top:-20px;"">")
                result.Append("                                <p class=""form-row form-row-wide"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"">")
                result.Append("                                        Pesan")
                result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("								       <textarea style=""height: 100px;"" name=""txtContactMessageReqCall"" id=""txtContactMessageReqCall"" placeholder=""Silahkan diisi.."" class=""form-control required""></textarea> ")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                        <div class=""row"" style=""margin-bottom: 0px;"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-top: -20px;"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom: 0px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"">")
                result.Append("                                        Captcha")
                result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                    <img src=""" + _rootPath + "wf/support/displayCaptcha.aspx"" style=""border:1.5px solid #ccc;border-radius:4px;"" />")
                result.Append("                                    <input type=""text"" id=""txtCaptcha"" name=""txtCaptcha"" class=""input-text"" style=""margin-top:5px;padding: 10px 5px 10px 10px; height: 20px;"" value="""" placeholder=""Masukan kode captcha diatas..."" />")
                result.Append("                                    <label id=""iCaptcha"" class=""invalid-tooltip"" style=""color: #b53838;margin-top: 25px; font-weight: bold; font-size: 10px; letter-spacing: unset;"">Kode captcha harus diisi</label>")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                            <div class=""row"">")
                result.Append("                                <div class=""col-sm-2""></div>")
                result.Append("                                <div class=""col-sm-8"" style=""margin-top: -20px;"">")
                result.Append("                                    <button style=""padding: 5px 20px;background-color: #e06660;border-color: #e06660; border-radius: 4px; font-family: arial; font-size: 13px;"" type=""button"" id=""btnRequestCall"" value=""KIRIM"" class=""btn btn-primary"" onclick=""javascript: doRequestCallHome();""  name=""btn-7"">KIRIM</button>")
                result.Append("                                </div>")
                result.Append("                                <div class=""col-sm-2""></div>")
                result.Append("                            </div>")
                result.Append("                        </div>")
                result.Append("                    </div>")
                result.Append("                </section>")

                'result.Append("        </div>")
                'result.Append("    </div>")
                'result.Append("  </div>")

                result.Append("            <div class=""modal-footer"" style=""display:none"">")
                result.Append("             </div>")

                result.Append("        </div>")
                result.Append("    </div>")
                result.Append("  </div>")
            Else
                result.Append("<div class=""modal fade"" id=""myModalRequestCall2"" role=""dialog"" style=""background-color: unset;z-index: 1040;"">")
                result.Append("    <div class=""modal-dialog"" style=""margin: -35px auto;"">")
                result.Append("        <div class=""modal-content"">")
                result.Append("            <div class=""modal-header"" style=""text-align:center;"">")
                result.Append("              <button type=""button"" class=""close"" data-dismiss=""modal"" name=""btn-8"">&times;</button>")
                result.Append("              <h4 class=""modal-title"">Hubungi Kami</h4>")
                result.Append("            </div><br>")

                'result.Append("	<div id=""previewMain"">")
                'result.Append("		<div class=""innerMain"">")
                'result.Append("			<div class=""contentMain"">")

                result.Append("                <section class=""section-wrap login-register pt-0 pb-30"">")
                result.Append("                    <div class=""container"" style=""width:100%;"">")
                result.Append("                      <div id=""wrapperformregist"" style=""width:auto;"">")
                result.Append("                       <div class=""row"" style=""margin-bottom: 20px;"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"">")
                result.Append("                                <p class=""form-row form-row-wide"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"" >")
                result.Append("                                        Nama Anda")
                result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                    <input type=""text"" id=""txtYourNameReqCall"" name=""txtYourNameReqCall"" class=""input-text"" placeholder=""Masukan nama.."" style=""margin-top:5px;padding: 10px 5px 10px 10px; height: 20px; width: 99.9%;"" value="""" />")
                result.Append("                                    <label id=""iYourNameReqCall"" class=""invalid-tooltip"" style=""color: #b53838;margin-top: 25px; font-weight: bold; font-size: 10px;    letter-spacing: unset;"">Nama harus diisi</label>")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                        <div class=""row"" style=""margin-bottom: 0px;"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-top: -45px;"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom: 0px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"">")
                result.Append("                                        Nomor Telepon")
                result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                    <input type=""text"" id=""txtNoHpReqCall"" name=""txtNoHpReqCall"" class=""input-text"" placeholder=""Masukan nomor Telepon aktif.."" style=""margin-top:5px;padding: 10px 5px 10px 10px; height: 20px; width: 99.9%;"" value="""" onkeyup=""javascript:toNumeric(this);"" />")
                result.Append("                                    <label id=""iHPReqCall"" class=""invalid-tooltip"" style=""color: #b53838;margin-top: 25px; font-weight: bold; font-size: 10px; letter-spacing: unset;"">Nomor Telepon harus diisi</label>")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                       <div class=""row"" style=""margin-bottom: 15px;"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-top: -25px;"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom: 15px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"" >")
                result.Append("                                        Email")
                'result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                    <input type=""text"" id=""txtYourEmailReqCall"" name=""txtYourEmailReqCall"" class=""input-text""placeholder=""Masukan Email.."" style=""margin-top:5px;padding: 10px 5px 10px 10px;height: 20px;width: 100%;"" value="""" />")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                        <div class=""row"" style=""margin-bottom: 33px;margin-right: 22px;display:none"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-bottom:0px;margin-top: -60px;"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom:unset;margin-bottom:5px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"">")
                result.Append("                                        Waktu Terbaik untuk menghubungi Anda")
                'result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                </p>")
                result.Append("                                <div class=""form-group"">")
                result.Append("                                    <div style=""width: 122%;padding-left: 5px;"" class=""input-group date form_datetime2 col-md-5"" data-date=""2019-07-16T05:25:00Z"" data-date-format=""dd MM yyyy HH:ii"" data-link-field=""dtp_input1"">")
                result.Append("                                        <input style=""width: 85%;margin-top: 0px;height: 25px;"" class=""form-control"" size=""16"" type=""text"" value=""" + Format(Now, "dd MMMM yyyy HH:mm") + """ readonly id=""txtContactTimesRequestCall"" name=""txtContactTimesRequestCall"" />")
                'result.Append("                                        <span class=""input-group-addon""><span class=""glyphicon glyphicon-remove""></span></span>")
                result.Append("					                    <span class=""input-group-addon""><span class=""glyphicon glyphicon-th""></span></span>")
                result.Append("                                    </div>")
                'result.Append("				                    <input class=""form-control"" id=""txtContactTimeReqCall"" value=""<%=txtContactTimeReqCall %>"" name=""txtContactTimeReqCall"" type=""hidden"" autocomplete=""off"" id=""dtp_input1""  /><br/>")
                result.Append("                                </div>")
                result.Append("                                <div id=""iContactTimeReqCall"" style=""margin-top: -19px;display:;"" >")
                result.Append("                                </div>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                        <div class=""row"" style=""margin-bottom: 33px;display:none"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-top:-20px;"">")
                result.Append("                                <p class=""form-row form-row-wide"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"">")
                result.Append("                                        Pesan")
                result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("								       <textarea style=""height: 100px; width: 108.7%;"" name=""txtContactMessageReqCall"" id=""txtContactMessageReqCall"" placeholder=""Silahkan diisi.."" class=""form-control required""></textarea> ")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                        <div class=""row"" style=""margin-bottom: 0px;"">")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                            <div class=""col-sm-8"" style=""margin-top: -20px;"">")
                result.Append("                                <p class=""form-row form-row-wide"" style=""margin-bottom: 0px;"">")
                result.Append("                                    <label class=""edit-profile"" style=""color: #979797; font-weight: bold; font-size: 14px; letter-spacing: unset; margin-bottom: 5px;"">")
                result.Append("                                        Captcha")
                result.Append("                                        <abbr class=""required"" title=""required"" style=""color: #999;"">*</abbr>")
                result.Append("                                    </label>")
                result.Append("                                    <img src=""" + _rootPath + "wf/support/displayCaptcha.aspx"" style=""border:1.5px solid #ccc;border-radius:4px;max-width:99%;width:99%"" />")
                result.Append("                                    <input type=""text"" id=""txtCaptcha"" name=""txtCaptcha"" class=""input-text"" style=""margin-top:5px;padding: 10px 5px 10px 10px; height: 20px; width: 99.9%;"" value="""" placeholder=""Masukan kode captcha diatas..."" maxlength=""5"" />")
                result.Append("                                    <label id=""iCaptcha"" class=""invalid-tooltip"" style=""color: #b53838;margin-top: 25px; font-weight: bold; font-size: 10px; letter-spacing: unset;"">Kode captcha harus diisi</label>")
                result.Append("                                </p>")
                result.Append("                            </div>")
                result.Append("                            <div class=""col-sm-2""></div>")
                result.Append("                        </div>")

                result.Append("                            <div class=""row"">")
                result.Append("                                <div class=""col-sm-2""></div>")
                result.Append("                                <div class=""col-sm-8"" style=""margin-top: -20px;"">")
                result.Append("                                    <button name=""btn-9"" style=""padding: 7px 27px;background-color: #e06660;border-color: #e06660; border-radius: 4px; font-family: arial; font-size: 13px;"" type=""button"" id=""btnRequestCall"" value=""KIRIM"" class=""btn btn-primary"" onclick=""javascript: doRequestCallHome();"" >KIRIM</button>")
                result.Append("                                </div>")
                result.Append("                                <div class=""col-sm-2""></div>")
                result.Append("                            </div>")
                result.Append("                        </div>")
                result.Append("                    </div>")
                result.Append("                </section>")

                'result.Append("        </div>")
                'result.Append("    </div>")
                'result.Append("  </div>")

                result.Append("            <div class=""modal-footer"" style=""display:none"">")
                result.Append("             </div>")

                result.Append("        </div>")
                result.Append("    </div>")
                result.Append("  </div>")
            End If
        Catch ex As Exception
            result = New StringBuilder
        End Try

        Return result.ToString

    End Function

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Load
        Dim q_tagRef As String = Request.QueryString("t")
        Dim q_domainRef As String = Request.QueryString("d")

        If IsNothing(q_tagRef) Then q_tagRef = ""
        If IsNothing(q_domainRef) Then q_domainRef = ""

         If IsPostBack Then
            
            Dim request_call_home As String = Request.Form("request_call_home")
            If Trim(request_call_home) = "1" Then
                Dim txtCaptcha As String = Request.Form("txtCaptcha")
                Dim txtYourNameReqCall As String = Request.Form("txtYourNameReqCall")
                Dim txtNoHpReqCall As String = Request.Form("txtNoHpReqCall")
                Dim txtYourEmailReqCall As String = Request.Form("txtYourEmailReqCall")
                txtContactTimesRequestCall = Request.Form("txtContactTimesRequestCall")
                txtChooseProperti = Request.Form("txtChooseProperti")
                Dim txtContactMessageReqCall As String = Request.Form("txtContactMessageReqCall")
                Dim responseRef = _responseRef
                Dim followUpAction = _followUpAction

                Dim newHp As String = txtNoHpReqCall

                Dim FirstHp As String = Left(txtNoHpReqCall, 1)

                If Trim(FirstHp) = "0" Then
                    newHp = txtNoHpReqCall.Remove(0,1)
                    ElseIf Trim(FirstHp) = "6" Then
                    newHp = txtNoHpReqCall.Remove(0,2)
                    ElseIf Trim(FirstHp) = "+" Then
                    newHp = txtNoHpReqCall.Remove(0,3)
                End If

                newHp = "62" + newHp
                                
                Dim temp As String = ""
                Dim cultureinfo As System.Globalization.CultureInfo = New System.Globalization.CultureInfo("en-GB")

                Dim ipAddress As String = HttpContext.Current.Request.UserHostAddress

                Dim dtCaptcha As New DataTable
                dtCaptcha = GetCaptchaInfo(Trim(txtCaptcha), ipAddress)

                If dtCaptcha.Rows.Count > 0
                    temp = insertRequestCallLeadV2(txtYourNameReqCall, newHp, txtYourEmailReqCall, _projectRef, responseRef, followUpAction, txtContactMessageReqCall)

                    updateCaptcha(ipAddress, Trim(txtCaptcha))
                End If

                If IsNumeric(temp) Then
                    Dim dt As New DataTable
                    'SendEmail([class].EmailType.registrationdeveloper, "Registration Developer Prime360.id ", New String() {Trim(registration_email)}, New String() {}, dt, "")
                    'SendEmail([class].EmailType.registrationdeveloper, "Registration Developer Prime360.id ", New String() {Trim(_emailNotif)}, New String() {}, dt, "")

                    Dim hash As New Hashtable
                    hash("note") = "Terima kasih. Kami akan memberikan update tentang "+_websiteProjectName+""
     
                    Response.Redirect(GetEncUrl(rootPath + "?", hash))
                Else
                    Response.Redirect(rootPath)
                End If
            End If

            Response.Redirect(_rootPath)
        
        Else

            If Not Request.Params("x") Is Nothing Then
                Dim param As Hashtable = GetDecParam(Request.Params("x"))

                note = MyURLEncode(param("note"))
                noteType = param("noteType")
                
                txtYourNameReqCall = param("txtYourNameReqCall")
                txtNoHpReqCall = param("txtNoHpReqCall")
                txtContactTimesRequestCall = param("txtContactTimesRequestCall")
                txtChooseProperti = param("txtChooseProperti")
                txtContactMessageReqCall = param("txtContactMessageReqCall")
                'txtEmail = param("txtEmail")
            End If

            'Dim resultPopup As New StringBuilder
            'resultPopup.Append(bindPopupRequestCall())
            'ltrModalRequestCall.Text = resultPopup.ToString()

            Dim resultPopup2 As New StringBuilder
            resultPopup2.Append(bindPopupRequestCall2())
            ltrModalRequestCall2.Text = resultPopup2.ToString()
        End If
            bindMenu()
            bindPopupRequestCall2()

    End Sub

End Class
